### ISSUE TITLE
can't run the story

### ISSUE THREAD

**Issue by isakgrozny** [jschomay/elm-interactive-story-starter#2]
When I try "npm start", it errors out as follows:

```
ERROR in ./src/Main.elm
Module build failed: Error: Compiler process exited with error Compilation failed
I cannot find module 'Engine'.

Module 'Main' is trying to import it.

Potential problems could be:
  * Misspelled the module name
  * Need to add a source directory or new dependency to elm-package.json

    at ChildProcess.<anonymous> (/Users/zack/Documents/writing/games/elm/elm-interactive-story-starter/node_modules/node-elm-compiler/index.js:291:27)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
 @ ./src/index.js 7:10-29
```

**Comment by jschomay** [comment]
Hi @isakgrozny, somehow I didn't notice your question till just now!  So sorry!

I hope you figured it out.  In either case, I've made some big updates since that time (http://blog.elmnarrativeengine.com/).  I'm not sure, but I think in your case you need to run `elm-package install` as well as `npm install` before `npm start` to get the elm packages.  I should have mentioned that in the readme, or make `npm i` do it for you.

I'll add that change right now in fact.

Thanks for your interest, and sorry for the long delay!

**Comment by jschomay** [comment]
Actually, just realized it already should install elm packages by default when you run `npm i`.  I'm going to close this issue as I think everything should work for you, but if you still have problems, let me know.
